-- 修复 project 表缺失的列（如果已存在则忽略报错）
ALTER TABLE `project` ADD COLUMN `ppt_object_name` VARCHAR(500) DEFAULT '' COMMENT 'MinIO中PPT对象名';
ALTER TABLE `project` ADD COLUMN `doc_object_name` VARCHAR(500) DEFAULT '' COMMENT 'MinIO中教案对象名';
ALTER TABLE `project` ADD COLUMN `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `project` ADD COLUMN `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
